#!/bin/bash

percent=$(acpi | grep -oP "[0-9]*%")
charge=$(acpi | grep -oP "(?<=: ).*?(?=, )")

if [ "$charge" == "Charging" ]
then
	power="[+]"
elif [ "$charge" == "Discharging" ]
then
	power="[$(acpi | grep -oP '\d+:\d+')]"
else
	power="[0]"
fi

echo "$percent $power"
