#!/bin/bash

percent=$(acpi | awk "/Battery 0:/" | grep -oP "\d+%")
charge=$(acpi | awk "/Battery 0:/" | grep -oP "(?<=: ).*?(?=, )")

if [ "$charge" == "Charging" ]
then
	power="[+]"
elif [ "$charge" == "Discharging" ]
then
	power="[$(acpi | grep -oP '\d+:\d+')]"
else
	power="[0]"
fi

echo "$percent $power"
