#!/bin/bash

#adapter=$(acpi -a | awk '/Adapter 0:/ { print $3 }')
percent=$(acpi -b | awk '/Battery 0:/ { print $4 }')
#remaining=$(acpi -b | awk '/Battery 0:/ { print $5 }')

#if [ "$adapter" == "on-line" ]
#then
#	status="+"
#else
#	status=$remaining
#fi

if [ "$percent" == "10%," ]
then
	notify-send -t 1000 -u critical -i battery-low "battery low"
fi

echo "$percent"
